name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use the appropriate JDK version for your project
          distribution: 'adopt'

      # Step 3: Build and run tests
      - name: Build and Test
        run: ./mvnw clean verify  # Use `mvnw` if your project has Maven Wrapper, or `mvn` if Maven is installed

  docker:
    runs-on: ubuntu-latest
    needs: build  # Run this job after the 'build' job is successful

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: docker build -t MatthewOduamafu/spring-boot-application:${{ github.sha }} .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push MatthewOduamafu/spring-boot-application:${{ github.sha }}
